### ISSUE TITLE
Code bugs

### ISSUE THREAD

**Issue by weipenegHU** [GfellerLab/MixMHCpred#1]
when I ran MixMHCpred according to the README file, the following error happens:
/ST_PRESICION/huweipeng/software/MixMHCpred-master/lib//MixMHCpred.x: 3: /ST_PRESICION/huweipeng/software/MixMHCpred-master/lib//MixMHCpred.x: Syntax error: Unterminated quoted string

**Comment by weipenegHU** [comment]
I ran MixMHCpredv1.0(2.0 not worked for me as mentioned above) successfully on TIL1 9mer peptides downloaded from this paper "Deciphering HLA-I motifs across HLA peptidomes improves neo-antigen predictions and identifies allostery regulating HLA specificity" but the predicted result is inconsistent to the one displayed in the paper.
```
predicted result for TIL1 9mer peptides 
In paper: A0201-1366 B1801-639 B3801-1498 C0501-509
Reproduce:A0201-1418 B1801-655 B3801-1466 C0501-473
```
I want to know that if I am doing something wrong though it is just a small margin between two results

**Comment by volpato30** [comment]
have you tried compiling the MixMHCpred.cc file on your machine?

i.e. in lib folder, run:
g++ -O3 MixMHCpred.cc -o MixMHCpred.x
