### ISSUE TITLE
 Inquiry Regarding Dataset from Recent Publication

### ISSUE THREAD

**Issue by KiAkize** [GfellerLab/MixMHCpred#10]
Hi, I recently read your team's latest publication, "MixMHCpred2.2 & PRIME2.0 (Cell Systems 2023)", and noticed that you have organized and made available a test dataset. I reviewed the contents of Table S3: List of peptides including both HLA-I ligands (i.e., positives) and random peptides (i.e., negatives) used to benchmark MixMHCpred2.2, related to Figure 2, available at https://data.mendeley.com/datasets/2kmmjp4tmm/1. 

This table states that the HLA-I ligands in the first ten datasets are sourced from Gfeller et al., while those in the last eleven datasets are from Pyke et al. However, I noticed that only the names of each sub-dataset, such as 3779-AMM_I, are provided. Could you please provide information on what alleles each of these 21 datasets corresponds to?

Looking forward to your response :)

**Comment by dagfeller** [comment]
Hi. 

The HLA typing was provided in the original studies, but I agree that I should have made it available. For conveniency, I'm attaching the file. 
[HLA_test.txt](https://github.com/GfellerLab/MixMHCpred/files/13753088/HLA_test.txt)
Please note that sample 1180157F from Pyke et al was not included as its HLA typing was not consistent with the immunopeptidomics data (see discussion in the paper).

I hope this helps.

**Comment by KiAkize** [comment]
Thanks a lot :)
