### ISSUE TITLE
Interpretation of the 4th column in the output file

### ISSUE THREAD

**Issue by volpato30** [GfellerLab/MixMHCpred#3]
the header for the fourth column in the output file says %Rank_bestAllele. However, it does not match the results from latter columns. 

For example, in the 33rd row of out_compare.txt file, the best allele is A0101, the 4th column is 1% but the rank for A0101 (6th column) is actually 0.3%.

May I ask why is that?

**Comment by dagfeller** [comment]
The % rank are recomputed based on all alleles and a distribution of peptides. Because peptides can have better score in the presence of other alleles, it is not suprising that the best %rank is higher than the one with the best allele. It's up to you to decide which values you want ot use.

**Comment by dagfeller** [comment]
The % rank are recomputed based on all alleles and a distribution of peptides. Because peptides can have better score in the presence of other alleles, it is not suprising that the best %rank is higher than the one with the best allele. It's up to you to decide which values you want ot use.
