### ISSUE TITLE
./MixMHCpred.x: cannot execute binary file

### ISSUE THREAD

**Issue by lisujun** [GfellerLab/MixMHCpred#5]
Hi, 

 I tried to run MixMHCpred but the error is 'cannot execute binary file'. Can you let me know how can I solve the problem ?

Thanks

**Comment by EdenGoldfarb** [comment]
For Linux:

After step 3), you also need to compile the MixMHCpred.cc code. Go to
MixMHCpred2.0.2/lib and compile with your favorite C++ compiler
(e.g. g++ -O3 MixMHCpred.cc -o MixMHCpred.x)
