### ISSUE TITLE
Negative scores and %rank

### ISSUE THREAD

**Issue by BioinformaNicks** [GfellerLab/MixMHCpred#6]
Hi,

I'm getting a negative score and %rank for some of my peptides, I'm not sure if this is normal?

**Comment by dagfeller** [comment]
Negative scores are expected, but negative %rank are unexpected. Can you send me the example?

**Comment by BioinformaNicks** [comment]
Ah, I'm truly sorry, there was a problem with my analysis script and it switched up two columns.
The score was negative, and I read in your paper that it is indeed to be expected. 
%Rank is not negative, I switched up the Score_Allele and %Rank columns.

Truly sorry for wasting your time like this, but really appreciate the quick responses!
